dist: trusty
sudo: required

language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0

          packages:
            - clang-6.0
            - g++-7
      env:
        - COMPILER="CC=clang-6.0 && CXX=clang++-6.0"

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - COMPILER="CC=gcc-7 && CXX=g++-7"

before_install:
  eval "${COMPILER}"

install:
  - mkdir build && cd build
  - cmake ..
  - make VERBOSE=1

script:
  make test
